use correct pointer type for coo shape
pydata/sparse pull request #421
Opened 2020-12-25 17:47 UTC by bnavigator

The suggested `self.self.coords_dtype` did not work for the construction of types.UniTuple():

```
[   73s] >       return self.data[ref(key)]
[   73s] E       TypeError: Failed in nopython mode pipeline (step: nopython mode backend)
[   73s] E       cannot create weak reference to 'numpy.dtype' object
```

But using numba's correct integer type for pointers works.

Fixes #420

2020-12-25 18:04 UTC, hameerabbasi requested changes
One minor change.

2020-12-25 18:04 UTC, hameerabbasi commented on sparse/_coo/numba_extension.py
> +        return types.UniTuple(types.intp, self.ndim)
I'd prefer not to hard-code.
```suggestion
        dt = numba.np.numpy_support.from_dtype(self.coords_dtype)
        return types.UniTuple(at, self.ndim)
```

2020-12-25 19:12 UTC, bnavigator commented on sparse/_coo/numba_extension.py
> +        return types.UniTuple(at, self.ndim)
```suggestion
        return types.UniTuple(dt, self.ndim)
```

2020-12-26 00:42 UTC, hameerabbasi approved these changes

2020-12-26 00:43 UTC, merged