Add fancy indexing support for DOK item assignment
pydata/sparse pull request #435
Opened 2021-03-03 06:05 UTC by DragaDoncila

Modify `__setitem__` to support a subset of advanced/fancy indexing where all dimensions are indexed. This uses @stschroe's gist [here](https://gist.github.com/stschroe/7c4660774835258c06b2be968eb49204#file-sparse_dok_indexer-py).

We also need `__getitem__`, but we thought we'd submit that as a separate PR.

2021-03-03 16:31 UTC, hameerabbasi commented
It would be nice to get the code coverage up -- Look into `pytest.raises` (there are uses in the tests) and try to hit everything and possibly remove dead code.

2021-03-04 05:04 UTC, DragaDoncila commented
Hi @hameerabbasi I've added a few more tests and it looks like it's hitting 100% of the diff. Please let me know if there's anything else you'd like to see!

2021-03-04 17:52 UTC, hameerabbasi requested changes

2021-03-04 17:52 UTC, hameerabbasi commented on sparse/_dok.py
> +        value = np.asanyarray(value, dtype=self.dtype)
```suggestion
        value = np.asarray(value, dtype=self.dtype)
```
`np.asanyarray` lets subclasses through. There are prominent subclasses of `np.ndarray` that don't follow the [Liskov Substitution Principle](https://en.wikipedia.org/wiki/Liskov_substitution_principle), and are therefore not fit for consumption by this function.

2021-03-04 17:52 UTC, hameerabbasi commented
This should be the last change needed -- Sorry for the slow feedback loop.

2021-03-04 19:37 UTC, DragaDoncila commented
Not slow at all! Thank you for the prompt reviews :smiley:

2021-03-04 19:43 UTC, hameerabbasi approved these changes

2021-03-04 19:44 UTC, merged

2021-03-04 19:45 UTC, hameerabbasi commented
Thanks @DragaDoncila! This is in!