allow for use of different dtypes in coords, indices, and indptr
pydata/sparse pull request #441
Opened 2021-03-11 22:00 UTC by daletovar

In this version, I've added a `storage_dtype` argument in the `COO` and `GCXS` constructors. For most operations, the result array will use the same storage dtype as the input array. There are a few places where the output is upcast to a larger dtype if the input dtype is too small. I decided to do this because in these situations no error is raised and the output is simply wrong. Where it doesn't make sense to upcast, I have it raise an error.

2021-03-12 11:36 UTC, hameerabbasi requested changes
A general comment: We should strive for 100% test coverage. If we cannot hit a line with a test, it is probably dead code anyway. In this particular instance, I see that most of the code here can be hit; but I'd like to see it tested since this is a major feature/refactor.

2021-03-12 11:36 UTC, hameerabbasi commented on sparse/_compressed/common.py
> +    total_nnz = sum([arr.nnz for arr in arrays[:-1]])
```suggestion
    total_nnz = sum(int(arr.nnz) for arr in arrays[:-1])
```

To make sure we avoid overflows, and don't construct a list.

2021-03-13 06:42 UTC, hameerabbasi requested changes
Just a few more remaining! Great work!

2021-03-13 06:42 UTC, hameerabbasi commented on sparse/_compressed/common.py
> +        indptr = indptr.astype(np.min_scalar_type(total_nnz))
This branch needs hitting or removing.

2021-03-13 06:42 UTC, hameerabbasi commented on sparse/_compressed/compressed.py
> +        raise ValueError(
So does this one.

2021-03-13 06:42 UTC, hameerabbasi commented on sparse/_utils.py
> +            raise ValueError(
As does this one.

2021-03-15 09:08 UTC, ivirshup commented
Thanks for looking into this more @daletovar! Minor naming suggestion: something like `index_dtype`/ `idx_dtype`? I feel like `storage_dtype` maybe be a bit too generic of a name.

2021-03-16 23:41 UTC, hameerabbasi approved these changes
LGTM, thanks @daletovar!

2021-03-16 23:41 UTC, merged