Fixed the issue #424
pydata/sparse pull request #447
Opened 2021-03-19 18:51 UTC by H4R5H1T-007

2021-03-19 18:54 UTC, hameerabbasi requested changes
Maybe cast these things to `float` so things happen automatically, without a try-catch?

2021-03-19 18:54 UTC, hameerabbasi commented on sparse/_utils.py
> +        density = 'undefined'
```suggestion
        density = np.Nan
```

2021-03-19 18:54 UTC, hameerabbasi commented on sparse/_utils.py
> +        storage_ratio = 'undefined'
```suggestion
        storage_ratio = np.man
```

2021-03-22 11:56 UTC, hameerabbasi requested changes
The test needs fixing.

2021-03-22 11:56 UTC, hameerabbasi commented on sparse/tests/test_coo.py
> +        html_table(sparse.COO.from_numpy(np.array(())))
The try catch is unnecessary, the test fails on an exception.

Also, we should check the result of density and storage ratio, that's where the original bug was.

2021-03-23 09:02 UTC, H4R5H1T-007 commented
Tests are failing in Windows environment @hameerabbasi sir. can you check what is error because I am unable to understand it.

2021-03-23 11:57 UTC, hameerabbasi requested changes

2021-03-23 11:57 UTC, hameerabbasi commented on sparse/tests/test_coo.py
> +    ground_truth = "<table>"
It'd be ideal if ground truth was a literal string, and you didn't have to construct it here.

Copy-pasting code from the function into the test is usually Bad.

2021-03-23 13:04 UTC, merged

2021-03-23 13:05 UTC, hameerabbasi commented
Thanks for your work on this, @H4R5H1T-007!

2021-03-23 13:06 UTC, H4R5H1T-007 commented
Thank You @hameerabbasi sir for your guidance to solve this issue. It helped me to learn a lot.