Improve matmul benchmark
pydata/sparse pull request #467
Opened 2021-04-24 22:48 UTC by sayandip18

This is WIP. More commits incoming.

2021-05-12 12:22 UTC, hameerabbasi requested changes
Maybe you could parametrize things instead of using multiple separate benchmarks?

2021-05-16 10:19 UTC, sayandip18 commented
If the changes are okay, I'll squash the commits

2021-05-16 10:24 UTC, hameerabbasi reviewed
I'd like one last change, parametrise all the things!

2021-05-16 10:24 UTC, hameerabbasi commented on benchmarks/benchmark_matmul.py
> +class Matmul_Sparse:
Maybe these two classes could also be parameterised.

Something like `dense_arg = [0, 1, None]`.

2021-05-17 10:47 UTC, hameerabbasi commented on benchmarks/benchmark_matmul.py
> +        self.y = sparse.random((100, 100), density=dens_arg, format=p)
This still produces a GCXS when the dense argument is `1.0`, what I meant in https://github.com/pydata/sparse/pull/467/files#r633073348 was that `0` means `self.x` should be `.todense()`, and `1` means the same for `self.y`.

2021-05-17 12:39 UTC, hameerabbasi commented on benchmarks/benchmark_matmul.py
> +        if(dens_arg==1):
```suggestion
        if(dens_arg==0):
```

2021-05-17 12:39 UTC, hameerabbasi commented on benchmarks/benchmark_matmul.py
> +        elif(dens_arg==0):
```suggestion
        elif(dens_arg==1):
```

2021-05-17 12:46 UTC, hameerabbasi approved these changes
Just waiting on CI to turn green.

2021-05-17 14:53 UTC, merged