Add `SDDMM` example
pydata/sparse pull request #674
Opened 2024-05-08 11:41 UTC by mtsokol

Hi @hameerabbasi,

This PR adds `SDDMM` example and upgrades Finch to the latest version. It needs https://github.com/willow-ahrens/finch-tensor/pull/42.

For my machine, running:
```bash
python examples/sddmm_example.py
```
gives:
```
Finch
iter: 0
iter: 1
iter: 2
Took 0.015560388565063477 s.

Numba
iter: 0
iter: 1
iter: 2
Took 39.91333301862081 s.

SciPy
iter: 0
iter: 1
iter: 2
Took 0.029975096384684246 s.
```

2024-05-08 11:47 UTC, mtsokol commented
I think density could be increased to `0.0001` so we have 100 non-zeros (more realistic?) - I get same performance.

2024-05-08 12:33 UTC, hameerabbasi requested changes
Two final changes then this is ready.

2024-05-08 12:33 UTC, hameerabbasi commented on examples/sddmm_example.py
> +        print(f"iter: {i}")
```suggestion
```

`print` statements have a large overhead

2024-05-08 12:33 UTC, hameerabbasi commented on examples/sddmm_example.py
> +            return sparse.sum(s[:, :, None] * (a[:, None, :] * b[None, :, :]), axis=-1)
We should go with what's fastest for each backend.
```suggestion
            return s * (a @ b)
```

2024-05-08 12:36 UTC, hameerabbasi commented
I'd actually like to test the examples as well. Can we add something like the following to CI:

```bash
# test_examples.sh
for example in $(find ./examples/ -iname *.py); do
  python $example
done

# in CI
source test_examples.sh
```

2024-05-08 12:57 UTC, hameerabbasi submitted a review, later dismissed

2024-05-08 13:00 UTC, hameerabbasi commented on examples/sddmm_example.py
> +    s = sps.random_array((LEN, LEN), format="coo", density=DENSITY, random_state=rng)
```suggestion
    s = sps.random_array((LEN, LEN), format="csr", density=DENSITY, random_state=rng)
```

CSR should be better for SciPy.

2024-05-09 09:41 UTC, mtsokol commented
Blocked by https://github.com/willow-ahrens/Finch.jl/issues/534

2024-05-09 09:54 UTC, mtsokol commented on examples/sddmm_example.py
> +    s = sps.random_array((LEN, LEN), format="coo", density=DENSITY, random_state=rng)
Done!

2024-05-09 15:34 UTC, mtsokol commented
Here's a debug output for Finch lazy mode plan:

<details>

```julia
Executing:
:(function var"##compute#410"(prgm)
      begin
          V = (((((((((((((((((((prgm.children[1]).children[2]).children[2]).children[3]).children[1]).children[1]).children[1]).children[2]).children[1]).children[2]).children[1]).children[1]).children[1]).children[1]).children[1]).children[1]).children[1]).children[1]).children[2]).tns.val::Tensor{SparseCOOLevel{2, Tuple{Int64, Int64}, Vector{Int64}, Tuple{PlusOneVector{Int32}, PlusOneVector{Int32}}, ElementLevel{0.0, Float64, Int64, PyArray{Float64, 1, true, true, Float64}}}}
          V_2 = ((((((((((((((((((((((((((((prgm.children[1]).children[2]).children[2]).children[3]).children[1]).children[1]).children[1]).children[2]).children[1]).children[3]).children[1]).children[1]).children[1]).children[1]).children[1]).children[1]).children[2]).children[1]).children[2]).children[1]).children[1]).children[1]).children[1]).children[1]).children[1]).children[1]).children[1]).children[2]).tns.val::Tensor{DenseLevel{Int64, DenseLevel{Int64, ElementLevel{0.0, Float64, Int64, PyArray{Float64, 1, true, true, Float64}}}}}
          V_3 = ((((((((((((((((((((((((((((prgm.children[1]).children[2]).children[2]).children[3]).children[1]).children[1]).children[1]).children[2]).children[1]).children[3]).children[1]).children[1]).children[1]).children[1]).children[1]).children[1]).children[2]).children[1]).children[3]).children[1]).children[1]).children[1]).children[1]).children[1]).children[1]).children[1]).children[1]).children[2]).tns.val::Tensor{DenseLevel{Int64, DenseLevel{Int64, ElementLevel{0.0, Float64, Int64, PyArray{Float64, 1, true, true, Float64}}}}}
          A0 = V::Tensor{SparseCOOLevel{2, Tuple{Int64, Int64}, Vector{Int64}, Tuple{PlusOneVector{Int32}, PlusOneVector{Int32}}, ElementLevel{0.0, Float64, Int64, PyArray{Float64, 1, true, true, Float64}}}}
          A0_2 = Tensor(Dense(SparseDict(Element{0.0, Float64}())))::Tensor{DenseLevel{Int64, SparseLevel{Int64, Finch.DictTable{Int64, Int64, Vector{Int64}, Vector{Int64}, Vector{Int64}, Dict{Tuple{Int64, Int64}, Int64}}, ElementLevel{0.0, Float64, Int64, Vector{Float64}}}}}
          @finch mode = :fast begin
                  A0_2 .= 0.0
                  for i1 = _
                      for i0 = _
                          A0_2[i1, i0] = A0[i0, i1]
                      end
                  end
                  return A0_2
              end
          A2 = V_2::Tensor{DenseLevel{Int64, DenseLevel{Int64, ElementLevel{0.0, Float64, Int64, PyArray{Float64, 1, true, true, Float64}}}}}
          A4 = V_3::Tensor{DenseLevel{Int64, DenseLevel{Int64, ElementLevel{0.0, Float64, Int64, PyArray{Float64, 1, true, true, Float64}}}}}
          A8 = Tensor(Dense(SparseDict(Element{0.0, Float64}())))::Tensor{DenseLevel{Int64, SparseLevel{Int64, Finch.DictTable{Int64, Int64, Vector{Int64}, Vector{Int64}, Vector{Int64}, Dict{Tuple{Int64, Int64}, Int64}}, ElementLevel{0.0, Float64, Int64, Vector{Float64}}}}}
          @finch mode = :fast begin
                  A8 .= 0.0
                  for i52 = _
                      for i51 = _
                          for i50 = _
                              A8[i50, i51] << + >>= (*)(A0_2[i50, i51], (*)(A2[1, i52], A4[1, i52]))
                          end
                      end
                  end
                  return A8
              end
          return (A8,)
      end
  end)
```

</details>

2024-05-09 18:03 UTC, willow-ahrens commented
Let's keep working on this until we see a speedup from fusion. I believe a fusion-based speedup should be achievable here, so it's a good goal to work towards.

2024-05-14 11:08 UTC, hameerabbasi approved these changes

2024-05-14 11:12 UTC, mtsokol commented
Right now we have precompilation of a few kernels. This causes a timeout of the first benchmark. Let me fix it.

2024-05-14 12:10 UTC, merged

2024-05-14 14:03 UTC, willow-ahrens commented
Thanks @mtsokol!