MNT: Move constructors to a direct style
pydata/sparse pull request #773
Opened 2024-09-12 14:37 UTC by mtsokol

Hi @hameerabbasi,

This PR moves MLIR constructors to the direct style (with: `sparse-assembler{direct-out=true}`).
I think it's more concise with this approach - `_constructors.py` LOC reduced by 50%, to 250.

Now all Tensors created from NumPy arrays or SciPy sparse arrays are owned and freed by the python side. 

The ones that are results of MLIR ops (like `add` right now) are allocated by MLIR and `owns_memory` in Tensor class is set to `False`. 

I haven't figured out yet how to correctly free MLIR allocated memrefs, (tried with `libc.free`) as I think there's still a memory leak after `sparse.add(tensor_a, tensor_b)`.

2024-09-12 15:40 UTC, hameerabbasi requested changes
Thanks @mtsokol! LGTM!

1. Let's make all members of `Tensor` private.
2. Let's store a list of `free`-able `memref` `str`s. So, for example, in `to_sps` let's store `["data"]`  for `dense`, then we will need to call `libc.free` on `data.allocated`. This will apply when we take ownership from MLIR only.
3. We need to store a reference to NumPy/SciPy objects when we create `Tensor`s from them, as we were doing before. The pattern for `_hold_self_ref_in_ret` will apply still in this case.

2024-09-12 15:40 UTC, hameerabbasi commented on sparse/mlir_backend/_constructors.py
> +            self.owns_memory = True
```suggestion
            self.owns_memory = False
```

2024-09-12 15:40 UTC, hameerabbasi commented on sparse/mlir_backend/_constructors.py
> +            self.owns_memory = True
```suggestion
            self.owns_memory = False
```

2024-09-12 15:40 UTC, hameerabbasi commented on sparse/mlir_backend/_constructors.py
> +            self.owns_memory = False
```suggestion
            self.owns_memory = True
```

2024-09-16 11:19 UTC, mtsokol commented on sparse/mlir_backend/_constructors.py
> +            self.owns_memory = True
Done!

2024-09-16 11:20 UTC, mtsokol commented on sparse/mlir_backend/_constructors.py
> +            self.owns_memory = True
Done!

2024-09-16 11:20 UTC, mtsokol commented on sparse/mlir_backend/_constructors.py
> +            self.owns_memory = False
Done!

2024-09-16 11:20 UTC, mtsokol commented
@hameerabbasi I applied all your review comments.

2024-09-16 12:30 UTC, hameerabbasi requested changes
A simplification to the memory logic: We can do most of this in `__del__`, check for `self._owns_memory` and then call `libc.free` on the constituent `memref`s if so.

2024-09-16 12:30 UTC, hameerabbasi commented on sparse/mlir_backend/_constructors.py
> +            weakref.finalize(self, finalizer, obj.get__fields_())
This can be moved to `__del__`.

2024-09-16 12:33 UTC, hameerabbasi commented on sparse/mlir_backend/_constructors.py
> +def freeme(obj: ctypes.Structure) -> None:
Maybe rename this to `free_memref`?

2024-09-16 12:43 UTC, mtsokol commented on sparse/mlir_backend/_constructors.py
> +            weakref.finalize(self, finalizer, obj.get__fields_())
Done!

2024-09-16 12:43 UTC, mtsokol commented on sparse/mlir_backend/_constructors.py
> +def freeme(obj: ctypes.Structure) -> None:
Done!

2024-09-16 14:59 UTC, merged